# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import anomaly_pb2 as anomaly__pb2


class AnomsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Expose = channel.unary_unary(
                '/pb.Anoms/Expose',
                request_serializer=anomaly__pb2.AnomRequest.SerializeToString,
                response_deserializer=anomaly__pb2.AnomResponse.FromString,
                )


class AnomsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Expose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Expose': grpc.unary_unary_rpc_method_handler(
                    servicer.Expose,
                    request_deserializer=anomaly__pb2.AnomRequest.FromString,
                    response_serializer=anomaly__pb2.AnomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Anoms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Anoms(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Expose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Anoms/Expose',
            anomaly__pb2.AnomRequest.SerializeToString,
            anomaly__pb2.AnomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
