# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomaly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranomaly.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n\x06Metric\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"*\n\x0b\x41nomRequest\x12\x1b\n\x07metrics\x18\x01 \x03(\x0b\x32\n.pb.Metric\"\x1f\n\x0c\x41nomResponse\x12\x0f\n\x07indices\x18\x01 \x03(\x05\x32\x36\n\x05\x41noms\x12-\n\x06\x45xpose\x12\x0f.pb.AnomRequest\x1a\x10.pb.AnomResponse\"\x00\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anomaly_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _globals['_METRIC']._serialized_start=54
  _globals['_METRIC']._serialized_end=133
  _globals['_ANOMREQUEST']._serialized_start=135
  _globals['_ANOMREQUEST']._serialized_end=177
  _globals['_ANOMRESPONSE']._serialized_start=179
  _globals['_ANOMRESPONSE']._serialized_end=210
  _globals['_ANOMS']._serialized_start=212
  _globals['_ANOMS']._serialized_end=266
# @@protoc_insertion_point(module_scope)
